services:
  static-server:
    image: static-html-nginx
    build: ./Static-server
    ports:
      - "8080:80"

  foosball-api:
    image: foosball-api
    build: ./foosball-api
    ports:
      - "7000:7000"