version: '3'

services:

  reverse-proxy:
    image: traefik
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./certs:/etc/traefik/certificates
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml


  static-server:
    image: static-html-nginx
    build: ./Static-server
    labels:
      - "traefik.enable=true"
      # Redirige les requêtes http
      - "traefik.http.routers.static-server-http.rule=Host(`localhost`)"
      - "traefik.http.routers.static-server-http.entrypoints=http"
      # Redirige les requêtes https
      - "traefik.http.routers.static-server.tls=true"
      - "traefik.http.routers.static-server.rule=Host(`localhost`)"
      - "traefik.http.routers.static-server.entrypoints=https"
    deploy:
      replicas: 3

  foosball-api:
    image: foosball-api
    build: ./foosball-api
    labels:
      - "traefik.enable=true"
      # Active la sticky-session
      - "traefik.http.services.foosball-api.loadbalancer.sticky.cookie=true"
      - "traefik.http.services.foosball-api.loadbalancer.sticky.cookie.name=my-sticky-cookie"
      # Redirige les requêtes http pour l'API
      - "traefik.http.routers.foosball-api-http.rule=Host(`localhost`) && PathPrefix(`/api`)"
      - "traefik.http.routers.foosball-api-http.entrypoints=http"
      # Redirige les requêtes https
      - "traefik.http.routers.foosball-api.tls=true"
      - "traefik.http.routers.foosball-api.rule=Host(`localhost`) && PathPrefix(`/api`)"
      - "traefik.http.routers.foosball-api.entrypoints=https"
      # Redirige les requêtes vers le port 7000
      - "traefik.http.services.foosball-api.loadbalancer.server.port=7000"
    deploy:
      replicas: 3

  portainer:
    image: portainer/portainer-ce
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.localhost`)"
      - "traefik.http.routers.portainer.entrypoints=https"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.routers.portainer-http.entrypoints=http"

volumes:
  portainer_data: